### ISSUE TITLE
Stop pilots from firing weapons that are compeltely out of range

### ISSUE THREAD

**Issue by Tyler799** [fat4eyes-mwo/mwo-simulator#13]
As stated in an earlier issue, pilots shouldn't fire when they're completely out of range. It's silly seeing a cheetah fire SPLs at a target 1500m away. 

Should be modified so pilots don't do that. It'd be even cooler if they had a small chance of doing it anyways based on their skill level (IE, a T1 almost never does that, but a T5 might do it fairly frequently) but just stopping it for now would be vast improvement. 

EDIT: This only occurs with "alpha no overheat" and "alpha when at zero heat" since other types are damage based they don't fire.

**Comment by fat4eyes-mwo** [comment]
You're right that this only happens in the Alpha No Overheat and Alpha At Zero Heat settings. I'll fix it at https://github.com/fat4eyes-mwo/mwo-simulator/issues/14. 

Unfortunately doing this based on player skill level is out of scope for the app (I don't have any data on player behavior and I'm not comfortable modelling something that detailed without any data. Making the wrong assumptions on something that complex without any real world data to back it up will just produce results that are not very useful).
