### ISSUE TITLE
"Alpha No Overheat" and "Alpha at zero heat" cause pilots to fire weapons inside min range

### ISSUE THREAD

**Issue by Tyler799** [fat4eyes-mwo/mwo-simulator#14]
Related to this issue: https://github.com/fat4eyes-mwo/mwo-simulator/issues/13

**Comment by fat4eyes-mwo** [comment]
Should be fixed in https://github.com/fat4eyes-mwo/mwo-simulator/commit/825b42cb1c56125235564781af169d4ab6b2f5cf
