### ISSUE TITLE
ams counts as damage

### ISSUE THREAD

**Issue by CarbonGuardian** [fat4eyes-mwo/mwo-simulator#21]
This simulator is amazing! thank you so much for taking the time to make it. 
Unfortunately when I use a build with ams, the ams is added to the damage dealt, which is incorrect ams doesn't do mech damage it only destroys missiles, pls fix to exclude ams damage.

Thank you and keep up this amazing work!

**Comment by fat4eyes-mwo** [comment]
Should be fixed in https://github.com/fat4eyes-mwo/mwo-simulator/commit/5d8291f324d3cb58179207cc42b597ccbdad77ca
