### ISSUE TITLE
"Alpha - No Overheat" stops working if a weapon is lost due to damage

### ISSUE THREAD

**Issue by Tyler799** [fat4eyes-mwo/mwo-simulator#5]
In other words, a 'Mech with 5 lasers loses a laser.

In the "alpha, no overheat" setting, this will stop it from firing for the rest of the match unless its firing setting is changed to a different one.

**Comment by fat4eyes-mwo** [comment]
Confirmed. Will change the fire pattern to ignore destroyed weapons on alpha.

**Comment by fat4eyes-mwo** [comment]
Should be fixed in https://github.com/fat4eyes-mwo/mwo-simulator/commit/a8f5c5b7da9ffd2427d2fdc521548becf6acc554
