### ISSUE TITLE
Allow a skill tree to be applied to a given 'Mech

### ISSUE THREAD

**Issue by Tyler799** [fat4eyes-mwo/mwo-simulator#9]
Skill trees play a massive part on the effectiveness of many 'Mechs, especially in the area of suitability since the skill tree stacks multiplicatively with inherent quirks. 

If we could import a tree from here somehow: https://kitlaan.gitlab.io/mwoskill/

That would be amazing.

**Comment by fat4eyes-mwo** [comment]
Implemented in 2017-08-13 update. You can access it by clicking Details->Skills->Load Skills in the mech pane.
